services:
  db:
    image: postgres:15-alpine
    container_name: cloudstorage_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloudstorage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: cloudstorage_s3_mock
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloudstorage_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cloudstorage
      - SECRET_KEY=prodsecretchangeinprod12345
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_S3_BUCKET=cloud-storage-bucket
      - AWS_S3_ENDPOINT_URL=http://localstack:4566
    ports:
      - "8000:8000"
    depends_on:
      - db
      - localstack

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloudstorage_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  localstack_data:
